# Generated by Django 6.0.3 on 2026-03-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('consumer_code', models.CharField(db_column='CONSUMER_CODE', primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(db_column='CONSUMER_NAME', unique=True)),
                ('mail_address', models.CharField(db_column='MAIL_ADDRESS')),
                ('gender', models.CharField(db_column='GENDER')),
                ('age', models.IntegerField(db_column='AGE')),
                ('address', models.CharField(db_column='ADDRESS')),
            ],
            options={
                'db_table': 'CONSUMER',
                'managed': True,
                'indexes': [models.Index(fields=['consumer_name'], name='consumer_name_index'), models.Index(fields=['gender'], name='consumer_gender_index')],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type_code', models.CharField(db_column='TYPE_CODE', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='TYPE_NAME')),
            ],
            options={
                'db_table': 'PRODUCT_TYPE',
                'managed': True,
                'indexes': [models.Index(fields=['type_name'], name='type_name_index')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.CharField(db_column='PRODUCT_CODE', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME')),
                ('price', models.IntegerField(db_column='PRICE')),
                ('type_code', models.ForeignKey(db_column='TYPE_CODE', on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.producttype')),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalePeriod',
            fields=[
                ('sales_code', models.CharField(db_column='SALES_CODE', primary_key=True, serialize=False)),
                ('sale_title', models.TextField(db_column='SALE_TITLE')),
                ('start_date', models.DateField(db_column='START_DATE')),
                ('end_date', models.DateField(db_column='END_DATE')),
            ],
            options={
                'db_table': 'SALE_PERIOD',
                'managed': True,
                'indexes': [models.Index(fields=['sale_title'], name='sale_period_index')],
            },
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField(db_column='DISCOUNT_RATE')),
                ('product_code', models.ForeignKey(db_column='PRODUCT_CODE', on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.product')),
                ('sales_code', models.ForeignKey(db_column='SALES_CODE', on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.saleperiod')),
            ],
            options={
                'db_table': 'SALES_INFO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('slip_code', models.CharField(db_column='SLIP_CODE', primary_key=True, serialize=False)),
                ('order_date', models.DateField(db_column='ORDER_DATE')),
                ('price', models.IntegerField(db_column='PRICE')),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('consumer_code', models.ForeignKey(db_column='CONSUMER_CODE', on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.consumer')),
                ('product_code', models.ForeignKey(db_column='PRODUCT_CODE', on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.product')),
                ('sales_code', models.ForeignKey(blank=True, db_column='SALES_CODE', null=True, on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.saleperiod')),
            ],
            options={
                'db_table': 'SLIP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_code', models.CharField(db_column='DELIVERY_CODE', primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(db_column='DELIVERY_DATE')),
                ('delivery_status', models.CharField(db_column='DELIVERY_STATUS')),
                ('finish_date', models.DateField(blank=True, db_column='FINISH_DATE', null=True)),
                ('slip_code', models.ForeignKey(db_column='SLIP_CODE', on_delete=django.db.models.deletion.PROTECT, to='coffee_shop.slip')),
            ],
            options={
                'db_table': 'DELIVERY',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='slip',
            index=models.Index(fields=['order_date'], name='order_date_index'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_date'], name='delivery_date_index'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_status'], name='delivery_status_index'),
        ),
    ]
