
--日ごとの商品別売上
CREATE VIEW DAILY_SALES_BY_PRODUCT AS  
SELECT  
   PR.PRODUCT_NAME   AS product_name
  ,SUM(SL.QUANTITY * SL.PRICE)     AS total_sales
  ,SUM(SL.QUANTITY)  AS total_quantity
  ,SL.ORDER_DATE     AS order_date
FROM SLIP    AS SL
JOIN PRODUCT AS PR
ON SL.PRODUCT_CODE = PR.PRODUCT_CODE
GROUP BY PR.ORDER_DATE,PR.PRODUCT_NAME

--日ごと売上
CREATE VIEW DAILY_SALES AS  
SELECT
   SUM(SL.QUANTITY * SL.PRICE)     AS 売上金額
  ,SUM(SL.QUANTITY)  AS 数量
  ,PR.ORDER_DATE     AS 日付
FROM SLIP    AS SL
JOIN PRODUCT AS PR
ON SL.PRODUCT_CODE = PR.PRODUCT_CODE
GROUP BY PR.ORDER_DATE

--商品区分ごとの売上
CREATE VIEW  TYPE_SALES AS
SELECT 
  PT.TYPE_NAME  AS 商品区分
 ,SUM(SL.QUANTITY * SL.PRICE) AS 売上金額
FROM PRODUCT AS PR
JOIN PRODUCT_TYPE AS PT
ON PR.TYPE_CODE  = PT.TYPE_CODE
JOIN SLIP AS SL
ON SL.PRODUCT_CODE = PR.PRODUCT_CODE
GROUP BY PT.TYPE_NAME
ORDER BY SUM(SL.QUANTITY * SL.PRICE) DESC


--性別毎の商品売上
CREATE VIEW GENDER_SALES AS 
SELECT
  PR.PRODUCT_NAME AS 商品名
 ,SUM(CASE WHEN CONSUMER.GENDER ='1' THEN SL.QUANTITY * SL.PRICE ELSE NULL END) AS 男性
 ,SUM(CASE WHEN CONSUMER.GENDER ='2' THEN SL.QUANTITY * SL.PRICE ELSE NULL END) AS 女性
FROM CONSUMER  AS CON
JOIN SLIP      AS SL
ON CON.CONSUMER_CODE = SL.CONSUMER_CODE
JOIN  PRODUCT AS PR
ON   SL.PRODUCT_CODE = PR.PRODUCT_CODE
GROUP BY 
  PR.PRODUCT_NAME




--リピーター 
--誰がよく買っているか
--パーテイションテーブルにして
CREATE VIEW VISIT  AS SELECT
    CONSUMER.CONSUMER_CODE AS 顧客コード
   ,CONSUMER.CONSUMER_NAME AS 顧客名
   ,MAX(DENSE_RANK() OVER W) AS 購入回数 
FROM CONSUMER
JOIN SLIP 
ON CONSUMER.CONSUMER_CODE = SLIP.CONSUMER_CODE
GROUP BY CONSUMER.CONSUMER_CODE,CONSUMER.CONSUMER_NAME,SL.ORDER_DATE
WINDOW W AS (PARTITION BY CONSUMER.CONSUMER_CODE ORDER BY SL.ORDER_DATE) ;